# Generated by Django 2.2.5 on 2019-09-28 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shakes', '0007_auto_20190928_0951'),
        ('users', '0002_auto_20190916_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='shakes.resume'),
        ),
    ]
