# Generated by Django 2.2.5 on 2019-09-28 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=30)),
                ('phone', models.CharField(default='', max_length=15)),
                ('address', models.CharField(default='', max_length=50)),
                ('exp', models.CharField(default='', max_length=250)),
                ('edu', models.CharField(default='', max_length=250)),
                ('act', models.CharField(default='', max_length=250)),
                ('skills', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.resume'),
        ),
    ]
