# Generated by Django 2.2.5 on 2019-09-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190928_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='additionDocs',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
