# Generated by Django 2.2.5 on 2019-09-28 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_additiondocs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='additionDocs',
            new_name='additionalDocs',
        ),
    ]
