# Generated by Django 2.2.5 on 2019-10-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20191008_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='additionalDocs',
            field=models.FileField(blank=True, default='profile_pics\\default.jpg', null=True, upload_to='resumes'),
        ),
    ]
