# Generated by Django 2.2.5 on 2019-10-09 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20191008_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='act',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='address',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='edu',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='email',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='exp',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='name',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='skills',
        ),
        migrations.AddField(
            model_name='resume',
            name='file',
            field=models.FileField(blank=True, default='profile_pics\\default.jpg', null=True, upload_to='resumes'),
        ),
    ]
