# Generated by Django 2.2.5 on 2019-10-09 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_resume_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='additionalDocs',
        ),
    ]
