# Generated by Django 2.2.5 on 2019-10-09 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_profile_additionaldocs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flyer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='flyer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='flyer',
            name='info',
        ),
        migrations.RemoveField(
            model_name='flyer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='flyer',
            name='website',
        ),
        migrations.AddField(
            model_name='flyer',
            name='file',
            field=models.FileField(blank=True, default='profile_pics\\default.jpg', null=True, upload_to='resumes'),
        ),
        migrations.AlterField(
            model_name='flyer',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AlterField(
            model_name='flyer',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
