# Generated by Django 2.2.5 on 2019-10-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20191008_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='file',
            new_name='resume_file',
        ),
        migrations.AlterField(
            model_name='flyer',
            name='file',
            field=models.FileField(blank=True, default='profile_pics\\default.jpg', null=True, upload_to='flyers'),
        ),
    ]
