# Generated by Django 2.2.5 on 2019-10-09 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20191008_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flyer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
    ]
