# Generated by Django 2.2.5 on 2019-10-09 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20191008_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flyer',
            name='file',
            field=models.FileField(default='profile_pics\\default.jpg', null=True, upload_to='flyers'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume_file',
            field=models.FileField(default='profile_pics\\default.jpg', null=True, upload_to='resumes'),
        ),
    ]
