# Generated by Django 2.2.5 on 2019-10-09 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20191008_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(upload_to='company_pics'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume_file',
            field=models.FileField(null=True, upload_to='resumes'),
        ),
    ]
