# Generated by Django 2.2.5 on 2019-10-09 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20191008_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='flyer',
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.resume'),
        ),
    ]
