# Generated by Django 2.2.5 on 2019-09-27 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shakes', '0002_meetup'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('startTime', models.DateField()),
                ('endTime', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
    ]
