# Generated by Django 2.2.5 on 2019-09-27 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shakes', '0003_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='event',
        ),
        migrations.AddField(
            model_name='meetup',
            name='_event',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shakes.event'),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
