# Generated by Django 2.2.5 on 2019-09-27 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shakes', '0004_auto_20190926_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetup',
            old_name='_event',
            new_name='eventObj',
        ),
    ]
