# Generated by Django 2.2.5 on 2019-09-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shakes', '0005_auto_20190926_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=50)),
                ('exp', models.CharField(max_length=250)),
                ('edu', models.CharField(max_length=250)),
                ('act', models.CharField(max_length=250)),
                ('skills', models.CharField(max_length=150)),
            ],
        ),
    ]
