# Generated by Django 2.2.5 on 2019-09-28 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190928_0953'),
        ('shakes', '0007_auto_20190928_0951'),
    ]

    operations = [
        migrations.DeleteModel(
            name='resume',
        ),
    ]
