# Generated by Django 2.2.5 on 2019-09-30 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shakes', '0010_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='LastUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
