# Generated by Django 2.2.5 on 2019-10-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shakes', '0013_auto_20191009_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='fileShared',
            field=models.CharField(default='profile_pics\\default.jpg', max_length=50),
        ),
    ]
